In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### carregar arquivo para o dataframe

In [38]:
df_exames = pd.read_csv('./datasets/exame_diabetes.csv')

### visualizar estrutura

In [39]:
df_exames.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_paciente  100 non-null    int64
 1   genero       100 non-null    str
 2   idade        100 non-null    int64
 3   peso         100 non-null    int64
 4   altura       100 non-null    int64
 5   resultado    100 non-null    int64
dtypes: int64(5), str(1)
memory usage: 4.8 KB

### apresentar as 10 primeiras linhas

In [40]:
df_exames.head(10)

   id_paciente genero  idade  peso  altura  resultado
0            1      M     46    83     165         98
1            2      F     23    83     164         82
2            3      M     39    71     154         93
3            4      F     26   103     165         95
4            5      M     27    55     176        100
5            6      M     64    93     190        117
6            7      F     21    70     182         90
7            8      F     60   101     179         84
8            9      F     63    83     189         92
9           10      F     65    78     175        121

In [41]:
df_exames.genero.unique()

<StringArray>
['M', 'F']
Length: 2, dtype: str

### remover coluna 'id_paciente'

In [42]:
## removendo a coluna id_paciente, pois não é relevante para o modelo
df_exames = df_exames.drop(columns=['id_paciente'])
df_exames.head()

  genero  idade  peso  altura  resultado
0      M     46    83     165         98
1      F     23    83     164         82
2      M     39    71     154         93
3      F     26   103     165         95
4      M     27    55     176        100

### converter uma variável categórica (genero) em númerica, usando one-hot encoding

In [43]:
## A coluna 'genero' é categórica, precisamos transformá-la em numérica para usar no modelo de machine learning
df_exames = pd.get_dummies(df_exames, columns=['genero'], dtype='int64')
df_exames.head()

   idade  peso  altura  resultado  genero_F  genero_M
0     46    83     165         98         0         1
1     23    83     164         82         1         0
2     39    71     154         93         0         1
3     26   103     165         95         1         0
4     27    55     176        100         0         1

In [44]:
df_exames.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   idade      100 non-null    int64
 1   peso       100 non-null    int64
 2   altura     100 non-null    int64
 3   resultado  100 non-null    int64
 4   genero_F   100 non-null    int64
 5   genero_M   100 non-null    int64
dtypes: int64(6)
memory usage: 4.8 KB